### PR TITLE
readme description edit

### PR DESCRIPTION
**Pull request by albiebabie**

### CODE REVIEW

**Comment by Rob-rls** [comment]
Nice job on the readme! 

My suggestion would be to keep the user stories with the plan file, so it is all in one place.

**Review by Rob-rls — CHANGES_REQUESTED** [review]
I@m just playing with this new feature.  
As per my comment above 🍔 
I suggest merging the user stories with the plan document

**Review by albiebabie — COMMENTED** [review]
I've added the user stories to the plan.md file. Hope that helps

**Comment by SlipperyJ** [comment]
:shipit:

**Pull request merged**
